"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import { RecoilRoot } from 'recoil';



const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <RecoilRoot>
        <body className="bg-gradient-to-b from-black to-green-900 h-full w-[100vw]">{children}</body>
      </RecoilRoot>
    </html>
  );
}
